Config = Config or {}

Config.RosterLink = {
    ['police'] = '',
    ['sheriff'] = '',
    ['sasp'] = '',
    ['bcso'] = '',
    ['sapr'] = '',
    ['sahp'] = '',
    ['fib'] = '',
    ['iaa'] = '',
    ['marshall'] = '',
    ['ambulance'] = '',
    ['judge'] = '',
}


Config.UseWolfknightRadar = true
--[[
Adds support for Wraith ARS 2X by WolfKnight98 (wk_wars2x)
https://github.com/WolfKnight98/wk_wars2x
To save on unnecessary database queries, in wk_wars2x/config.lua set 'CONFIG.use_sonorancad = true'
This will only check plates of vehicles that have been occupied by a player
--]]

Config.OnlyShowOnDuty = false

Config.Fuel = "ed-fuel" -- "ed-fuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'Cinayet/Cinayet Girişimi',
    [2] = 'Kişi ve Kurumlara karşı işlenen suçlar',
    [3] = 'Soygun Suçları',
    [4] = 'Silah Bulundurma/Magandalık',
    [5] = 'Uyuşturucu',
    [6] = 'Araçlar',
    [7] = 'Kamu Düzenini Bozma/Kamu Güvenliğini Tehlikeye Atma',
    [8] = 'Kamuya ve Kamu Mülküne Karşı İşlenen Suçlar',
    [9] = 'Çeşitli Suçlar',
    [10] = 'Kamu Gücünün Usulsüz Kullanımı Sonucu Ortaya Çıkan Suçlar',
    [11] = 'Trafik Suçları',
    [12] = 'İş Hukukuna Muhalefet Sonucu Ortaya Çıkan Suçlar/Vergi Suçları',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Ateşli Silah ile Kasıtlı Cinayet', class = 'Hapishane', id = 'P.C. 1001', months = 99999999, fine = 0, color = 'green'},
        [2] = {title = 'Kesici Delici Sopa Aletler ile Kasıtlı Cinayet', class = 'Hapishane', id = 'P.C. 1002', months = 99999999, fine = 0, color = 'orange'},
        [3] = {title = 'Devlet Çalışanını Öldürmek', class = 'Hapishane', id = 'P.C. 1003', months = 99999999, fine = 0, color = 'orange'},
        [4] = {title = 'Taksirle Adam Öldürme', class = 'Hapishane', id = 'P.C. 1004', months = 75, fine = 0, color = 'red'},
        [5] = {title = 'Cinayet Girişimi', class = 'Hapishane', id = 'P.C. 1005', months = 35, fine = 30000, color = 'red'},
        [6] = {title = 'Devlet Çalışanına Cinayet Girişimi', class = 'Hapishane', id = 'P.C. 1006', months = 50, fine = 35000, color = 'red'},
        [7] = {title = 'Adam Kaçırma', class = 'Hapishane', id = 'P.C. 1007', months = 25, fine = 20000, color = 'red'},
    },
    [2] = {
        [1] = {title = 'Taksirle Adam Yaralama', class = 'Hapishane', id = 'P.C. 2001', months = 30, fine = 15000, color = 'blackblue'},
        [2] = {title = 'Devlet Çalışanına Darp Girişimi', class = 'Kamu Hizmeti', id = 'P.C. 2002', months = 40, fine = 5000, color = 'blackblue'},
        [3] = {title = 'Devlet Çalışanını Rehin Alma', class = 'Hapishane', id = 'P.C. 2003', months = 20, fine = 10000, color = 'blackblue'},
        [4] = {title = 'Devlet Çalışanına Tehdit', class = 'Kamu Hizmeti', id = 'P.C. 2004', months = 10, fine = 2000, color = 'blackblue'},
        [5] = {title = 'Ateşli Silahla Soygun', class = 'Kamu Hizmeti', id = 'P.C. 2005', months = 10, fine = 0, color = 'blackblue'},
        [6] = {title = 'Ateşli Silahla Kasıtlı Adam Yaralama', class = 'Hapishane', id = 'P.C. 2006', months = 25, fine = 10000, color = 'blackblue'},
        [7] = {title = 'Kesici, Delici ve ya Darp Edici Aletle Kasıtlı Adam Yaralama', class = 'Hapishane', id = 'P.C. 2007', months = 15, fine = 7500, color = 'blackblue'},
        [8] = {title = 'Tecavüz', class = 'Hapishane', id = 'P.C. 2008', months = 999999999, fine = 0, color = 'blackblue'},
        [9] = {title = 'Fuhuş', class = 'Para Cezası', id = 'P.C. 2009', months = 0, fine = 100, color = 'blackblue'},
        [10] = {title = 'Kamu Görevlisine Tutuklanma Ve Ya Departman içerisinde Ağır Hakaret ve Polise Fiziksel Müdahale', class = 'Kamu Hizmeti', id = 'P.C. 2010', months = 25, fine = 5000, color = 'blackblue'},
        [11] = {title = 'Kamu Görevlisine Mukavemet', class = 'Kamu Hizmeti', id = 'P.C. 2011', months = 15, fine = 2500, color = 'blackblue'},
        [12] = {title = 'Özel Mülke Zorla ve yahut İzinsiz Girme', class = 'Kamu Hizmeti', id = 'P.C. 2012', months = 15, fine = 5000, color = 'blackblue'},
    },
    [3] = {
        [1] = {title = 'Ev Soygunu', class = 'Kamu Hizmeti', id = 'P.C. 3001', months = 10, fine = 2500, color = 'pink'},
        [2] = {title = 'Market Soygunu', class = 'Kamu Hizmeti', id = 'P.C. 3002', months = 25, fine = 4000, color = 'pink'},
        [3] = {title = 'vezne soygunu', class = 'Kamu Hizmeti', id = 'P.C. 3003', months = 45, fine = 20000, color = 'pink'},
        [4] = {title = 'Merkez Bankası Soygunu', class = 'Hapishane', id = 'P.C. 3004', months = 10, fine = 750, color = 'pink'},
        [5] = {title = 'Kuyumcu Soygunu', class = 'Hapishane', id = 'P.C. 3005', months = 20, fine = 0, color = 'pink'},
        [6] = {title = 'Sivil Vatandaşı Soyma', class = 'Kamu Hizmeti', id = 'P.C. 3006', months = 15, fine = 10000, color = 'pink'},
        [7] = {title = 'Devlet Memurunu Soyma', class = 'Hapishane', id = 'P.C. 3007', months = 35, fine = 20000, color = 'pink'},
    },
    [4] = {
        [1] = {title = 'Ateşli Silah Bulundurma', class = 'Para Cezası', id = 'P.C. 4001', months = 0, fine = 15000, color = 'yellow'},
        [2] = {title = 'Delici, Kesici Silah Bulundurma', class = 'Para Cezası', id = 'P.C. 4002', months = 0, fine = 10000, color = 'yellow'},
        [3] = {title = 'Magandalık', class = 'Kamu Hizmeti', id = 'P.C. 4003', months = 20, fine = 7500, color = 'yellow'},
    },
    [5] = {
        [1] = {title = 'Uyuşturucu Madde Üretimi', class = 'Kamu Hizmeti', id = 'P.C. 5001', months = 20, fine = 10000, color = 'purple'},
        [2] = {title = 'Uyuşturucu Bulundurma', class = 'Kamu Hizmeti', id = 'P.C. 5002', months = 10, fine = 300, color = 'purple'},
        [3] = {title = 'Uyuşturucu Satışı Yapma', class = 'Kamu Hizmeti', id = 'P.C. 5003', months = 15, fine = 10000, color = 'purple'},
        [4] = {title = 'İllegal Bölgede Bulunma', class = 'Kamu Hizmeti', id = 'P.C. 5004', months = 20, fine = 10000, color = 'purple'},
    },
    [6] = {
        [1] = {title = 'Devlet Aracı Hırsızlığı', class = 'Kamu Hizmeti', id = 'P.C. 6001', months = 20, fine = 5000, color = 'olivedrab'},
        [2] = {title = 'Araç Hırsızlığı', class = 'Kamu Hizmeti', id = 'P.C. 6002', months = 10, fine = 5000, color = 'olivedrab'},
        [3] = {title = 'Araç Çalmaya Teşebbüs', class = 'Kamu Hizmeti', id = 'P.C. 6003', months = 5, fine = 2000, color = 'olivedrab'},
        [4] = {title = 'Araç Kundaklama', class = 'Kamu Hizmeti', id = 'P.C. 6004', months = 25, fine = 5000, color = 'olivedrab'},
        [5] = {title = 'Araç Parçalama ', class = 'Kamu Hizmeti', id = 'P.C. 6005', months = 20, fine = 5000, color = 'olivedrab'},
    },
    [7] = {
        [1] = {title = 'Adaleti Önlemek', class = 'Hapishane', id = 'P.C. 7001', months = 25, fine = 0, color = 'blue'},
        [2] = {title = 'Tutuklamadan Kaçmak', class = 'Hapishane', id = 'P.C. 7002', months = 10, fine = 0, color = 'blue'},
        [3] = {title = 'İllegal Örgütlenme', class = 'Hapishane', id = 'P.C. 7003', months = 0, fine = 100000, color = 'blue'},
        [4] = {title = 'Eşgal Gizleme', class = 'Para Cezası', id = 'P.C. 7004', months = 30, fine = 5000, color = 'blue'},
        [5] = {title = 'Suça Yatalıklık', class = 'Para Cezası', id = 'P.C. 7005', months = 0, fine = 0, color = 'blue'},
        [6] = {title = 'Asılsız İhbar', class = 'Kamu Hizmeti', id = 'P.C. 7006', months = 10, fine = 2000, color = 'blue'},
        [7] = {title = 'Yalancı Şahitlik', class = 'Kamu Hizmeti', id = 'P.C. 7007', months = 15, fine = 1000, color = 'blue'},
        [8] = {title = 'Kara Para Bulundurmak', class = 'Hapishane', id = 'P.C. 7008', months = 15, fine = 2000, color = 'blue'},
        [9] = {title = 'Kara Para Bozmak ve Bununla Alakalı İşlem Yapmak', class = 'Hapishane', id = 'P.C. 7009', months = 0, fine = 0, color = 'blue'},
    },
    [8] = {
        [1] = {title = 'Sorgu Düzenine Uymama', class = 'Kamu Hizmeti', id = 'P.C. 8001', months = 10, fine = 500, color = 'orange'},
        [2] = {title = 'Kamu Alanlarına İzinsiz Giriş', class = 'Kamu Hizmeti', id = 'P.C. 8002', months = 15, fine = 1000, color = 'orange'},
        [3] = {title = 'Hapishaneden Kaçış', class = 'Hapishane', id = 'P.C. 8003', months = 0, fine = 0, color = 'orange'},
        [4] = {title = 'Sorgu Sırasında Yalan İfade Verme', class = 'Hapishane', id = 'P.C. 8004', months = 10, fine = 1000, color = 'orange'},
    },
    [9] = {
        [1] = {title = 'Irkçılık', class = 'Kamu Hizmeti', id = 'P.C. 9001', months = 10, fine = 1000, color = 'brown'},
        [2] = {title = 'Devlet Malına Zarar Verme', class = 'Kamu Hizmeti', id = 'P.C. 9002', months = 10, fine = 1000, color = 'brown'},
        [3] = {title = 'Kamu Huzurunu Bozma', class = 'Kamu Hizmeti', id = 'P.C. 9003', months = 10, fine = 2000, color = 'brown'},
        [4] = {title = 'Mühür Bozma', class = 'Para Cezası', id = 'P.C. 9004', months = 0, fine = 250000, color = 'brown'},
        [5] = {title = 'Yasa Dışı Bahis Oynamak', class = 'Hapishane', id = 'P.C. 9005', months = 0, fine = 150, color = 'brown'},
        [6] = {title = 'Yasa Dışı Bahis Oynatmak', class = 'Hapishane', id = 'P.C. 9006', months = 20, fine = 15000, color = 'brown'},
        [7] = {title = 'Kaçak Avcılık', class = 'Para Cezası', id = 'P.C. 9007', months = 0, fine = 5000, color = 'brown'},
        [8] = {title = 'Kimlik Taşımama', class = 'Para Cezası', id = 'P.C. 9008', months = 0, fine = 3000, color = 'brown'},
        [9] = {title = 'Hakaret', class = 'Kamu Hizmeti', id = 'P.C. 9009', months = 10, fine = 1000, color = 'brown'},
    },
    [10] = {
        [1] = {title = 'Kamu Görevinin Usulsüz Olarak Üstlenilmesi', class = 'Kamu', id = 'P.C. 10001', months = 20, fine = 10000, color = 'pink'},
        [2] = {title = 'Görev Tanımının Usulsüz Olarak Aşılması', class = 'Para Cezası', id = 'P.C. 10002', months = 0, fine = 15000, color = 'pink'},
        [3] = {title = 'Kamu Görevlisinin Orantısız Güç Kullanımı', class = 'Para Cezası', id = 'P.C. 10003', months = 10, fine = 20000, color = 'pink'},
        [4] = {title = 'Kamuya Ait Malın Satışı veya Kamu Dışına Aktarılması', class = 'Hapis Cezası', id = 'P.C. 10004', months = 0, fine = 0, color = 'pink'},
    },
    [11] = {
        [1] = {title = 'Vur Kaç', class = 'Para Cezası', id = 'P.C. 10005', months = 0, fine = 1500, color = 'gold'},
        [2] = {title = 'Hız Sınırlarının İhlali', class = 'Para Cezası', id = 'P.C. 10006', months = 0, fine = 3500, color = 'gold'},
        [3] = {title = 'Trafik Işıklarına Uymama', class = 'Para Cezası', id = 'P.C. 10007', months = 0, fine = 500, color = 'gold'},
        [4] = {title = 'Uyarıcı veya Uyuşturucu Madde Etkisi Altındayken Araç Kullanımı', class = 'Para Cezası', id = 'P.C. 10008', months = 20, fine = 5000, color = 'gold'},
        [5] = {title = 'Kontrolsüz/Dikkatsiz Araç Kullanımı', class = 'Para Cezası', id = 'P.C. 10009', months = 0, fine = 500, color = 'gold'},
        [6] = {title = 'Ehliyetsiz Araç Kullanımı', class = 'Para Cezası', id = 'P.C. 10010', months = 10, fine = 1000, color = 'gold'},
        [7] = {title = 'Hatalı Park', class = 'Para Cezası', id = 'P.C. 10011', months = 0, fine = 500, color = 'gold'},
        [8] = {title = 'Polisin Dur İhtarına Uymama', class = 'Para Cezası', id = 'P.C. 10012', months = 10, fine = 2000, color = 'gold'},
    },
    [12] = {
        [1] = {title = 'Vergi Denetimini Sabote Etme', class = 'Kamu Hizmeti', id = 'P.C. 10013', months = 10, fine = 0, color = 'beechwood'},
        [2] = {title = 'Vergi Denetimi Esnasında Gereken Kayıtları Usulüne Uygun Olarak Sunmama', class = 'Para Cezası', id = 'P.C. 10014', months = 0, fine = 0, color = 'beechwood'},
        [3] = {title = 'Vergi Kaçırma', class = 'Para Cezası', id = 'P.C. 10015', months = 0, fine = 0, color = 'beechwood'},
        [4] = {title = 'Haksız Rekabet', class = 'Para Cezası', id = 'P.C. 10016', months = 0, fine = 0, color = 'beechwood'},
        [5] = {title = 'Vergi Denetimi Esnasında Hazır Bulunmama', class = 'Para Cezası', id = 'P.C. 10017', months = 0, fine = 10000, color = 'beechwood'},
        [6] = {title = 'Faaliyet ve Ruhsat Kapsamı Dışında Bulunan Ürünün Satışı', class = 'Para Cezası', id = 'P.C. 10018', months = 10000, fine = 75, color = 'beechwood'},
    },
}

Config.PoliceJobs = {
    ['police'] = true,
    ['sheriff'] = true,
    ['sasp'] = true,
    ['bcso'] = true,
    ['sapr'] = true,
    ['sahp'] = true,
    ['fib'] = true,
    ['iaa'] = true,
    ['marshall'] = true,
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
}

Config.DojJobs = {
    ['judge'] = true,
    ['lawyer'] = true,
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['police'] = {
		["min"] = 10,
	},
    ['sheriff'] = {
		["min"] = 10,
	},
    ['sasp'] = {
		["min"] = 10,
	},
    ['bcso'] = {
        ["min"] = 10,
	},
    ['sapr'] = {
		["min"] = 10,
	},
    ['sahp'] = {
        ["min"] = 10,
	},
    ['fib'] = {
		["min"] = 10,
	},
    ['iaa'] = {
        ["min"] = 10,
	},
    ['marshall'] = {
		["min"] = 10,
	},
    ['ambulance'] = {
		["min"] = 10,
	},
    ['judge'] = {
        ["min"] = 0,
	},
    ['lawyer'] = {
		["min"] = 10,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = { 
    [1] = vector3(442.97, -1020.61, 28.59),
    [2] = vector3(852.81, -1346.81, 26.06),
    [3] = vector3(389.02, -1621.73, 29.29),
    [4] = vector3(1822.25, 3689.07, 33.97),
    [5] = vector3(-466.89, 6014.83, 31.34),
    [6] = vector3(-146.92, -1175.02, 23.77),
}
