shared_script '@ulasdmrc/shared_fg-obfuscated.lua'
shared_script '@ulasdmrc/ai_module_fg-obfuscated.lua'
fx_version 'cerulean'
game 'gta5'
description 'QB-StreetRaces'
version '1.2.0'
client_script 'client/main.lua'
server_script'server/main.lua'
lua54 'yes'
