Config = {}
Config.UseTruckerJob = false -- true = The shops stock is based on when truckers refill it | false = shop inventory never runs out
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.FirearmsLicenseCheck = false -- Whether a arms dealer checks for a firearms license
Config.ShopsInvJsonFile = './json/shops-inventory.json' -- json file location
Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}
Config.Products = {
    ["normal"] = {
        [1] = {
            name = "tosti",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 150,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [17] = {
            name = "phone",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 17,
        },
    },
    ["liquors"] = {
        [1] = {
            name = "beer",
            price = 7,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 10,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 12,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["pastane"] = {
        [1] = {
            name = "birthdaycake",
            price = 1500,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "slicedcake",
            price = 150,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "milk",
            price = 100,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "tod",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
    },
    ["maske"] = {
        [1] = {
            name = "blackbandana",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "tshirtmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "scarecrowmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "monkeymask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "longnose",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "silvermask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "goldmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "bagmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "balaclava",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "balaclava2",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "chinesemask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "clownmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "gorillamask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "horsemask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "unicornmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "skullmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "sockmask",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 17,
        },
    },
    ["weedshop"] = {
        [1] = {
            name = "joint",
            price = 10000,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weed_nutrition",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "empty_weed_bag",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "rolling_paper",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        }
    },
    ["market"] = {
        [1] = {
            name = "black_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "blue_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "classic_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "gold_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "green_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "pink_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "red_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "white_phone",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "heardring",
            price = 100000,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "radio",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "camera",
            price = 10000,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
    },
    ["alkol"] = {
        [1] = {
            name = "beer",
            price = 100,
            amount = 5,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 150,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 150,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "grapejuice",
            price = 200,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
    },
    ["bisiklet"] = {
        [1] = {
            name = "skateboard",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "bmx",
            price = 5000,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "binoculars",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "lockpick",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "cleaningkit",
            price = 1000,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "repairkit",
            price = 2500,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "advancedrepairkit",
            price = 5000,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "parachute",
            price = 3000,
            amount = 10,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "diving_fill",
            price = 500,
            amount = 10,
            info = {},
            type = "item",
            slot = 10,
        },
    },
    ["eczane"] = {
        [1] = {
            name = "bandage",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "painkillers",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "walkstick",
            price = 500,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
    },
}
Config.Locations = {
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(24.47, -1346.62, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(26.45, -1315.51, 29.62, 0.07)
    },

    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(549.13, 2670.85, 42.16, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2556.66, 380.84, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(372.66, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ["247supermarket10"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ["247supermarket11"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ["247supermarket12"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ["247supermarket13"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ["247supermarket14"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    ["247supermarket15"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ["247supermarket16"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ["247supermarket17"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ["247supermarket18"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ["247supermarket19"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    ["247supermarket20"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(812.88, -782.04, 26.17, 271.36),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(812.88, -782.04, 26.17, 271.36)
    },

    ["247supermarket21"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-548.99, -583.05, 34.68, 180.23),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Market",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-548.99, -583.05, 34.68, 180.23)
    },

    -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(978.46, 39.07, 74.88, 64.0),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Chips",
        ["products"] = Config.Products["casino"],
        ["showblip"] = true,
        ["blipsprite"] = 617,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(972.6, 9.22, 81.04, 233.38)
    },

    -- ["casinobar"] = {
    --     ["label"] = "Casino Bar",
    --     ["coords"] = vector4(968.13, 29.85, 74.88, 208.86),
    --     ["ped"] = 'a_m_y_smartcaspat_01',
    --     ["scenario"] = "WORLD_HUMAN_VALET",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-wine-bottle",
    --     ["targetLabel"] = "Open Casino Bar",
    --     ["products"] = Config.Products["liquor"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.8,
    --     ["blipcolor"] = 2,
    --     ["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    -- },

    -- San Andreas Park Locations
    -- ["pastane"] = {
    --     ["label"] = "Pastane Dükkanı",
    --     ["coords"] = vector4(-534.63, -611.3, 34.68, 86.67),
    --     ["ped"] = 's_f_y_clubbar_01',
    --     ["scenario"] = "WORLD_HUMAN_VALET",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Pastane Dükkanı",
    --     ["products"] = Config.Products["pastane"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.6,
    --     ["blipcolor"] = 12,
    --     ["delivery"] = vector4(-534.63, -611.3, 34.68, 86.67)
    -- },

    -- ["weedshop"] = {
    --     ["label"] = "Tobbaco Dükkanı",
    --     ["coords"] = vector4(-1248.94, -1449.23, 4.37, 37.32),
    --     ["ped"] = 'ig_stretch',
    --     ["scenario"] = "WORLD_HUMAN_VALET",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Tobbaco Dükkanı",
    --     ["products"] = Config.Products["weedshop"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.6,
    --     ["blipcolor"] = 12,
    --     ["delivery"] = vector4(-1248.94, -1449.23, 4.37, 37.32)
    -- },

    -- ["eczane"] = {
    --     ["label"] = "Eczane Dükkanı",
    --     ["coords"] = vector4(-1255.48, -1434.52, 4.37, 121.15),
    --     ["ped"] = 'u_f_y_beth',
    --     ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Eczane Dükkanı",
    --     ["products"] = Config.Products["eczane"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.6,
    --     ["blipcolor"] = 12,
    --     ["delivery"] = vector4(-1255.48, -1434.52, 4.37, 121.15)
    -- },

    -- ["manav"] = {
    --     ["label"] = "Manav Dükkanı",
    --     ["coords"] = vector4(-1253.52, -1444.49, 4.37, 35.97),
    --     ["ped"] = 'cs_old_man2',
    --     ["scenario"] = "WORLD_HUMAN_VALET",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Manav Dükkanı",
    --     ["products"] = Config.Products["manav"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 628,
    --     ["blipscale"] = 0.4,
    --     ["blipcolor"] = 5
    -- },

    -- ["maske"] = {
    --     ["label"] = "Maske Dükkanı",
    --     ["coords"] = vector4(-568.97, -586.34, 34.68, 270.76),
    --     ["ped"] = 'u_m_m_streetart_01',
    --     ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Maske Dükkanı",
    --     ["products"] = Config.Products["maske"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.6,
    --     ["blipcolor"] = 12,
    --     ["delivery"] = vector4(-568.97, -586.34, 34.68, 270.76)
    -- },

    -- ["market"] = {
    --     ["label"] = "Teknoloji Mağazası",
    --     ["coords"] = vector4(-528.19, -582.66, 34.68, 179.94),
    --     ["ped"] = 'ig_isldj_03',
    --     ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Teknoloji Mağazası",
    --     ["products"] = Config.Products["market"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 402,
    --     ["blipscale"] = 0.8,
    --     ["blipcolor"] = 0
    -- },

    -- ["alkol"] = {
    --     ["label"] = "Alkol Dükkanı",
    --     ["coords"] = vector4(-523.07, -617.02, 34.68, 54.04),
    --     ["ped"] = 'cs_movpremmale',
    --     ["scenario"] = "WORLD_HUMAN_VALET",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Alkol Dükkanı",
    --     ["products"] = Config.Products["alkol"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 628,
    --     ["blipscale"] = 0.4,
    --     ["blipcolor"] = 5
    -- },

    -- ["bisiklet"] = {
    --     ["label"] = "Bisiklet Dükkanı",
    --     ["coords"] =  vector4(-523.54, -582.62, 34.68, 121.71),
    --     ["ped"] = 'cs_lifeinvad_01',
    --     ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-shopping-basket",
    --     ["targetLabel"] = "Bisiklet Dükkanı",
    --     ["products"] = Config.Products["bisiklet"],
    --     ["showblip"] = false,
    --     ["blipsprite"] = 628,
    --     ["blipscale"] = 0.4,
    --     ["blipcolor"] = 5
    -- },

    ["alkols"] = {
        ["label"] = "Alkol Dükkanı",
        ["coords"] = vector4(-1831.74, -1172.06, 13.02, 152.77),
        ["ped"] = 's_f_y_clubbar_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Alkol Dükkanı",
        ["products"] = Config.Products["alkol"],
        ["showblip"] = false,
        ["blipsprite"] = 628,
        ["blipscale"] = 0.4,
        ["blipcolor"] = 5
    }
}


