shared_script '@ulasdmrc/shared_fg-obfuscated.lua'
shared_script '@ulasdmrc/ai_module_fg-obfuscated.lua'

fx_version 'cerulean'
game 'gta5'
description 'QB-TruckRobbery'
version '1.2.0'
shared_script 'config.lua'
server_script 'server/main.lua'
client_script 'client/main.lua'
lua54 'yes'
