QBCore = exports["qb-core"]:GetCoreObject()
PlayerData = {}

oyunayarlari = {
    ["klasik"] = {
        ["dogruluk"] = {
            "Hayatında hiç yalan söyledin mi?",
            "En sevdiğin yemek nedir?",
            "En sevmediğin yemek nedir?",
            "Birini hiç kıskandın mı? Kimdi?",
            "En sevdiğin renk nedir?",
            "Seni en mutlu eden anı hatırlıyor musun?",
            "Hiç bir arkadaşının sırrını söyledin mi?",
            "En sevdiğin müzik türü nedir?",
            "En çok hangi mevsimi seversin?",
            "Hiçbir şey yapmadan bir gününü nasıl geçirirdin?",
            "Şimdiye kadar kaç kez kalp kırdın?",
            "Hiç birinin kalbini kırdın mı?",
            "Hayatındaki en kötü kararı verdiğin zaman hatırlıyor musun?",
            "Hiç birisine aşık oldun mu?",
            "En sevdiğin film nedir?",
            "Hayatında kaç kez kandırıldın?",
            "Hiç kaçıp gitmek istedin mi?",
            "En sevdiğin hayvan nedir?",
            "Şimdiye kadar en utanç verici anın neydi?",
            "En sevdiğin şarkıcı ya da grubu söyleyebilir misin?",
            "En sevdiğin kitap nedir?",
            "Hayatının en güzel anını anlatabilir misin?",
            "Hiç birisine sır vermeden önce düşündün mü?",
            "En sevdiğin oyun nedir?",
            "En çok hangi tatil beldesinde kalmak istersin?",
            "Hiç birisi için ağladın mı?",
            "En sevdiğin spor nedir?",
            "En sevdiğin dizi nedir?",
            "Hiç birisi için yalan söyledin mi?",
            "En sevdiğin çizgi film karakteri kimdir?",
            "Hiç başka bir ülkeye gitmek istedin mi? Gitmek istediğin yer neresi?",
            "En sevdiğin tatlı nedir?",
            "Hiç kalp kırıklığına uğradın mı?",
            "Hiç bir arkadaşının sırrını sakladın mı?",
            "En sevdiğin marka nedir?",
            "En sevdiğin restoran nedir?",
            "Hiç kavga ettin mi? Kimle?",
            "En sevdiğin hobi nedir?",
            "Hiç birisi için yalan söylemek zorunda kaldın mı?",
            "En sevdiğin elbise rengi nedir?",
            "Hiç birisine yalan söyledin mi?",
            "En sevdiğin yazar kimdir?",
            "Hayatında hiç pişman oldun mu?",
            "En sevdiğin meyve nedir?",
            "Hiç başka bir şehre taşınmak istedin mi? Taşınmak istediğin yer neresi?",
            "En sevdiğin sporcu kimdir?",
            "Hiç sana karşı haksızlık yapıldığını hissettin mi? Ne oldu?",
            "En sevdiğin marka hangi telefon?",
            "Hiç birisini özledin mi?",
            "En sevdiğin çizgi roman hangisi?",
            "Hiç sana karşı yalan söylendiğini hissettin mi?",
            "En sevdiğin araba markası nedir?",
            "Hiç kimseye söyleyemediğin bir sırrın var mı?",
            "En sevdiğin oyun konsolu hangisi?",
            "Hiç birisine karşı önyargılı oldun mu?",
            "En sevdiğin animasyon filmi nedir?",
            "Hiç birisi seni üzdü mü? Kimdi?",
            "En sevdiğin sanatçı kimdir?",
            "Hiç birisi için ağladın mı? Kimdi?",
            "En sevdiğin tatil yeri neresidir?",
            "Hiç korkunç bir rüya gördün mü? Ne hakkındaydı?",
            "En sevdiğin pasta nedir?",
            "Hiç birisi seni aşağıladı mı? Kimdi?",
            "En sevdiğin çay türü nedir?",
            "Hiçbir şey yapmadan bir hafta sonunun nasıl geçirdiğini hayal edebiliyor musun?",
            "En sevdiğin aktör kimdir?",
            "Hiç aşk acısı çektin mi? Kimdi?",
            "En sevdiğin şarkı nedir?",
            "Hiç birisine karşı kin duydun mu? Kimdi?",
            "En sevdiğin balık türü nedir?",
            "Hiç birisine bağırdın mı?",
            "En sevdiğin yabancı dil hangisidir?",
            "Hiç birisi seni mutlu etti mi? Kimdi?",
            "En sevdiğin restoranın yemeği nedir?",
            "Hiç birisi seni hayal kırıklığına uğrattı mı? Kimdi?",
            "En sevdiğin plaj hangisi?",
            "Hiçbir şey yapmadan bir hafta sonunun nasıl geçirdiğini hayal edebiliyor musun?",
            "En sevdiğin kahve türü nedir?",
            "Hiç birisi seni terk etti mi? Kimdi?",
            "En sevdiğin oyun hangisi?",
        },
        ["cesaret"] = {
            "İnsanların önünde şarkı söyle.",
            "Komik bir dans yap.",
            "En sevdiğin şarkıyı tersten söyle.",
            "En yakındaki kişiye sarıl ve onu sevdiğini söyle.",
            "Telefonunda rastgele bir kişiye mesaj at ve 'merhaba' de.",
            "En utanç verici fotoğrafını açıkla.",
            "Karşındaki kişiyle dans et.",
            "Hava kararana kadar dışarıda kal.",
            "Kendine bir şarkı bestele ve söyle.",
            "Sokakta bir yabancıya selam ver ve onunla konuş.",
            "En komik sesinle bir şarkı söyle.",
            "Ellerini bağla ve bir dakika boyunca düşünce ifade et.",
            "Birine seni güldürebileceği en komik şakayı yapmasını söyle.",
            "En sevdiğin hayvanın taklidini yap.",
            "En sevdiğin müzik tarzı dışındaki bir şarkıyı söyle.",
            "Elini saçma bir şeye sok ve bir dakika boyunca beklet.",
            "Birinin yüzüne krem sür ve fotoğrafını çek.",
            "Karşındaki kişinin telefonuna bir mesaj gönder ve bir şarkı söylemesini iste.",
            "Yüksek sesle bir çocuk şarkısı söyle.",
            "En sevdiğin yemek malzemesini ağzına al ve bir dakika beklet.",
            "Gözlerini bağla ve odada yürümeye çalış.",
            "Karşındaki kişinin yüzüne süt çırp ve fotoğrafını çek.",
            "Sesi çıkmayacak şekilde bir şarkı söyle.",
            "Bir dakika boyunca yerinde zıpla.",
            "En sevdiğin film repliğini söyle.",
            "Karşındaki kişinin en sevdiği şeyi yapmasını iste.",
            "En sevdiğin hayvanın taklidini yaparak bir dakika boyunca dans et.",
            "Kendine ve başka bir kişiye aynı şeyi söyleyerek, kimin daha iyi söylediğini bulun.",
            "Yerden bir şey alırken öne eğil ve beş saniye boyunca beklet.",
            "Sırtında bir başka kişiye binerek yarım dakika boyunca dolaş.",
            "Kendine tuhaf bir saç stili yap.",
            "Bir dakika boyunca kendine bir şarkı bestele.",
            "En sevdiğin yemek hakkında bir hikaye anlat.",
            "Karşındaki kişiye aynı anda bir şarkı söyleyin.",
            "Yerden bir şey alırken başka bir kişinin yardımı olmadan eğil ve beş saniye beklet.",
            "İnsanların önünde şarkı söyle.",
            "Bir bardak tuzlu su iç.",
            "Bir çift çorapla eldiven giy ve böyle 10 dakika kal.",
            "Bir tuvalet kağıdı rulosuyla bir şarkı söyle.",
            "Bir yabancıya 'Seni seviyorum' de.",
            "En sevdiğin şarkıyı baş aşağı söyle.",
            "5 dakika boyunca bağırarak konuş.",
            "Sokakta yabancılara şaka yap.",
            "En utanç verici anını anlat.",
            "Dilini burun deliğine değdir.",
            "Bir şarkıyı kendi yaptığın sözlerle söyle.",
            "Yere düşen bir şey almak için bir yere eğil ve orada 30 saniye kal.",
            "Bir yemek tarifi anlat, ama yalnızca harflerle konuş.",
            "Arkadaşının telefonuna bir şaka mesajı yaz.",
            "En kötü dans hareketlerinden birini yap.",
            "Aynanın önünde 1 dakika boyunca kendine bak ve gülümse.",
            "Bir yabancının fotoğrafını çek ve ona göstermeden önce Instagram'a yükle.",
            "Bir nesneyi en iyi arkadaşına hediye et.",
            "Önünde olmayan bir kişi hakkında şarkı söyle.",
            "10 saniye boyunca yerde yuvarlan.",
            "En sevmediğin yemeği dene.",
            "Bir kelimeyi en uzun şekliyle yazarak söyle.",
            "En utanç verici fotoğrafını göster.",
            "Rastgele bir sayfayı aç, 10. satırdaki 5. kelimeyi söyle.",
            "5 dakika boyunca sadece Türkçe bilmiyormuş gibi konuş.",
            "Arkadaşının en sevdiği şarkıyı söyleyerek onu taklit et.",
            "En sevdiğin karakterin kıyafetlerini giy.",
            "Kulak memenin üzerine birkaç saniye dilini tut.",
            "Kendini bir hayvan gibi taklit et.",
            "En sevdiğin arkadaşının en sevdiği yemeği pişir.",
            "Sağ elini sol elinle değiştir ve böyle 10 dakika kal.",
            "Sokakta yürürken bir yabancıya sarıl.",
            "En sevdiğin film sahnesini canlandır.",
            "Bir yabancıya iltifat et.",
            "En utanç verici anını Snapchat'e kaydedip arkadaşınla paylaş.",
            "Saçını tamamen tarzına ters şekilde yap.",
            "Ellerini başının arkasında birleştir ve böyle 5 dakika kal.",
            "En sevdiğin yemek hakkında 3 farklı yalan söyle.",
            "Ellerini buzlu suya sok ve 30 saniye beklet.",
            "Bir tur boyunca çoraplarınla elini kullanarak yürü.",
            "Gözlerini bağla ve sadece kokulara dayanarak bir yiyecek türünü tahmin et.",
            "İnsanların önünde şarkı söyle.",
            "Birisi için bir şiir yaz ve o kişiye oku.",
            "3 dakika boyunca karnını açıkta bırakarak göbek dansı yap.",
            "Önündeki insanlara seni rahatsız eden bir şeyler söyle.",
        }
    },
    ["cilginparti"] = {
        ["dogruluk"] = {
            "Buradaki insanlar arasından kiminle çıkmak isterdin?",
            "Hayatında yaptığın en utanç verici şey ne?",
            "İlk görüşte aşka inanır mısın?",
            "Biriyle sonsuza kadar yaşamak istesen bu kim olurdu?",
            "Son erkek veya kız arkadaşınla nasıl ayrıldınız?",
            "Burada sana göre en kötü ilişkiyi hangi çift geçirir?",
            "Kişisel kahramanın kim?",
            "Burada en sevmediğin veya en az sevdiğin kişi kim?",
            "En büyük korkun ne?",
            "Birinin sana söylediği en son sırrı dökül.",
            "Hoşlandığın kişi kim?",
            "Buradan birisini köle almak istesen bu kim olurdu? ne yaptırmak isterdin?",
            "Beş kelimeyle kendini tanımla!",
            "En son kiminle ne kavgası ettin?",
            "Bu odada herkes hakkında fikrini açıkla.",
            "Birine aşık mısın? aşıksan onu biraz tanımla.",
            "1 yıl boyunca bir adada mahsur kalsan yanına ne alırdın?",
            "Tekrar doğma şansın olsaydı ne olmak isterdin?",
            "Burada en çekici bulduğun erkek/kız kim?",
            "Kim kötü bir ebeveyn olur?",
        },
        ["cesaret"] = {
            "Daha önce hiç yakın arkadaşlarından birine aşık oldun mu?",
            "Bir arkadaşınla sanki yabancıymışsın gibi flört et.",
            "Bize bir çocuk şarkısı söyle.",
            "Herkes yer değiştirsin!",
            "Günün geri kalanı boyunca arkadaşların tarafından seçilen bir kıyafeti giy",
            "Mümkün olduğu kadar fazla insan içermek üzere grupça kucaklaşın.",
            "Gece boyunca her tuvalete çıkman gerektiğinde karşı cinsten biriyle beraber gitmek zorundasın.",
            "5 tur boyunca bir kişiye Daddy/Mommy diye seslen.",
            "1 tur boyunca sağındaki insanın kucağında otur.",
            "2 tur boyunca oyundan atıldın!",
            "Diğerleri tarafından seçilen birisi ile dans et.",
            "Televizyondan ünlü bir kişinin taklidini yap.",
            "Sağındaki insanın taklidin yaparak onunla dalga geç.",
            "Bu odadaki birini taklit et ve diğerlerinin tahmin etmesine izin ver!",
            "Herkes hep beraber bir şarkı söylemeli. Hangi şarkı olacağına sen karar ver!",
            "Karşı cinsten biriyle eşleş, ikiniz ilk bebeklerine sahip olmak üzere olan mutlu bir çiftsiniz. 5 dakika boyunca bir doğum sahnesi canlandırın!",
            "Oynayan herkesi 5 saniyeliğine öp.",
            "Sol tarafındaki kişi birini seçsin ve o kişiye çıkma teklifi et!",
            "Komik bir grup fotoğrafı çekilip sosyal medyada paylaşın!",
            "Hiç durmadan 3 dakika boyunca kendini anlat!",
        }
    },
    ["ekstrem"] = {
        ["dogruluk"] = {
            "Eğer biri senin hayatın hakkında bir film yapsaydı ismi ne olurdu? Rolünü kim oynardı?",
            "En kötü öpüşmen hangisiydi?",
            "Hiç hesabı ödemeden bir restorandan ayrıldın mı?",
            "Hiç sevgilini aldattın mı?",
            "Odadaki oyuncular hakkında ne düşünüyorsun?",
            "Masturbasyon yaptığın en uygunsuz yer neresi?",
            "En sevdiğin porno sitesi?",
            "Bu odadaki en güzel kişi kim?",
            "Şehirdeki en kıskandığın kişi kim?",
            "Seni eski sevgilinle tekrar bir araya getirebilecek şey nedir?",
            "Tanıdığın en sinir bozucu kişi kim",
            "Yediğin en garip şey ne?",
            "Bir ünlü olsan hangisi olurdun?",
            "Daha önce hiç çıplak yüzdün mü?",
            "Sence en çekici pornocu kim?",
            "Bir insanda en nefret ettiğin şey ne?",
            "Eğer fiziksel görünüşünle ilgili bir şeyi değiştirme şansın olsa ne olur?",
            "Sağ tarafındaki kişiye tanıdığın biriyle seks yapıp yapmadığını sor.",
            "Daha önce hiç karşı cinse ait bir iç  çamaşırı giydiniz mi?",
            "Hiç aynı cinsten birine abayı yaktın mı?",
            "Cep telefonun olmadan dayanabileceğin en uzun süre sence ne kadar?",
            "İlk nerede seviştin?",
            "Aşık olduğun biri varmı ?",
            "Bu odadaki tüm insanlar arasında kiminle çıkmak isterdin?",
            "Arkadaşının sevgilisi olsa dahi o karşı cinse bir şeyler hissettin mi?",
            "Buradaki kişiler arasında en kötü giyinen kim?",
            "Buradaki kişiler arasında en seksi giyinen kim?",
            "Buradaki kişiler arasında en güzel giyinen kim?",
            "Sence zeka mı güzellik mi?",
            "Daha önce hiç bir erkek arkadaşının kardeşini yada arkadaşını öptün mü?",
            "En kötü alışkanlığın ne?",
            "Sinirini bozan şey ne?",
            "Hak etmeyen birine yaptığın en kötü şey neydi?",
            "Ağzına aldığın en iğrenç şey ne?",
            "Ağladığın en salak sebep neydi?",
            "Hiç çok sarhoşluktan yatağını ıslattın mı?",
            "Seks esnasında çok ses çıkarır mısın?",
            "En sevdiğin oyuncak hayvanının ismi neydi?",
            "Bu odada kiminle takılmak en kolay",
            "Yapıp da tamamen utanç duyduğun bir şeyden bahset.",
            "Fetiş Sahibi misin?",
        },
        ["cesaret"] = {
            "Yanında insanın telefonundaki bir kişiye müstehcen şeyler yazmasına izin ver.",
            "Sağındaki insanla tişörtünü çıkart.",
            "Bir kişinin göbek deliğine dil at.",
            "Odadaki en güzel kızla oynaş",
            "İstediğin 2 oyuncuyu (Karşı cins) birbirleriyle öpüştür.",
            "Sağ tarafındaki kişinin ayağının altını yala.",
            "Bir kızın göğüslerinin arasından bir shot iç",
            "Oyunculardan birinin (sen seç) ayak parmağını, bir kulak memesini ve dirseğini yala.",
            "Herkesi dudağından öp",
            "Sol tarafındaki kişiye sadece dudaklarını kullanarak bir şeker ver.",
            "Birisi seni tokatlasın.",
            "Sağ tarafdaki bir oyuncuyla oynaş.",
            "2 dakika boyunca karşı cinsten biriyle seviş.",
            "Herkesi etrafında topla 10 saniye boyunca dön ve karşına çıkanı öp.",
            "Sağındaki kişi sana bir şey söylesin ve twitter'da bunu paylaş.",
            "Birinin göbek deliğinden alkol iç.",
            "Kendi ayak parmağını öp.",
            "Herkese kendinle ilgili utanç verici bir olay anlat.",
            "Striptiz yap.",
            "Birini seç ve götüne şaplak atmasına izin ver.",
            "15 saniye duvarla seviş.",
            "Seninle fransız öpücüğü yapacak birini seç",
            "Alkolü kafana dik.",
            "Herkesin ayağını kokla ve kokularını oyla.",
        }
    },
    ["cift"] = {
        ["dogruluk"] = {
            "Kız/erkek arkadaşını aldatır mıydın?",
            "Hangisi seni heyecanlandırır? Derin bir öpücük mü, poponu avuçlamam mı yoksa vücudumu vücuduna yaslamam mı?",
            "Bir filmden ya da kitaptan seni gerçekten azdıran bir seks sahnesini anlat",
            "Eğer sevgiliniz 45 kilo alırsa seks sırası aynı zevki alıcağınızı düşünür müsün?",
            "Aldatmaya en çok yaklaştığın zaman hangisiydi?",
            "Diyelim ki ev yapımı bir seks videosu çekeceğiz. Sahneyi ve tam olarak ne yapacağımızı anlat.",
            "Bir sonraki seks yapışımızda ne olarak giyinmemi istersin?",
            "Hangisi seni daha çok tahrik eder: porno izlemek mi yoksa bir seks videosu çekmek mi?",
            "Dövme veya piercing yaptırabileceğim en seksi yer neresi?",
            "Partnerinin senden yapmanı istediği en edepsiz şey ne?",
            "Bağlanma sorunların var mı? Seks bağımlılı gibi?",
            "Sevgilin tamam dese aldatır mıydın?",
            "En sevdiğin seks müziği ne?",
            "Mükemmel romantik bir buluşma sana göre nasıl olur?",
            "Sevgiline söylediğin en büyük yalan neydi?",
            "Yatakta beni hangi hayvana benzetirdin?",
            "Eski sevgiline hala bir şeyler hissediyor musun?",
            "Sevgilin üçlü seksi kabul etse sen eder miydin?",
            "Yatakta bana söylemekten aşırı utandığın şey ne?",
            "Bir ilişkide ilk adımı atmayı mı tercih edersin yoksa sevgilinin mi bunu yapmasını tercih edersin?",
            "Bir ay boyunda sadece bir pozisyonda seks yapabilsen hangi pozisyonu seçerdin?",
            "Bir ünlüyle takılmana izin versem bu kim olurdu?",
            "Sence kavga sonrası barışma seksi, günlük seksten daha mı iyi? -Hayır diyen vurduruyordur xd",
            "Her zaman denemek istediğin seks pozisyonu hangisi?",
            "ilk erkek/kız arkadaşınla neden ayrıldın?",
            "Hangi ilişkiyi tercih ederdin: Vahşi, tutkulu veya sessiz sakin olan?",
            "Bir eleştirmenmiş gibi davran ve yakınlaştığımız en son seferdeki performansımı değerlendir.",
            "Hiç yetişkin filmlerinde denemek istediğin bir şey gördün mü?",
            "Yatakda edepsiz konuşmalar mı yapmamı yoksa yüksek sesle inlememi mi tercih edersin?",
            "Beni Bağlamayı mı tercih edersin yoksa üzerimden çikolata sosu yalamayı mı?",
            "Seks esnasında adını çığlık atarak söylesem mi daha seksi yoksa benimle yaptığın şeyi sevdiğimi söylesem mi?",
            "Yatakta duymaktan hoşlandığın edepsiz bir lafı söyle.",
            "Partnerinin yataktaki performansını 1'den 10'a kadar puanla.",
            "Sence hangi kıyafetle en seksi gözüküyorum?",
            "Seksi bir film çekecek olsan adı ne olurdu?",
            "Erkek/kız arkadaşınla ilgili en sinir bozucu şey nedir?",
            "Birlikte yaptığımız en müstehcen şey ne? Nesinin hoşuna gittiğini ayrıntılı olarak anlat.",
            "Daha önce hiç partnerinize ilişkiniz sırasında veya öncesinde başka insanlarla beraber olma konusunda yalan söylediniz mi?",
            "şimdiye kadar yaşadığın en iyi orgazmı anlat.",
            "Alır mısın yoksa daha çok verir misin?",
            "Bir günde en çok kaç kere mastürbasyon yaptın?",
            "Seni kıskanç yapan şey nedir?",
            "Uçakta seks partisine katılmak ister miydin?",
            "Üç kelimeyle yataktaki kişiliğini anlat",
            "Yatakta kelepçeli olsam bana ne yapardın?",
            "Popomu bir yabancıya anlatacak olsan ne söylerdin?",
            "Senin iş yerinde seks yaptığımızı düşün. Sahneyi anlat.",
            "Eşinizin başka biriyle seks yapmasını izler miydiniz?",
            "Benimle seks yapmak istediğin en garip yer neresi? Anlat.",
            "Boyu mu işlevi mi?",
        },
        ["cesaret"] = {
            "Parmağım dondurmaymış gibi davran.",
            "Tişörtünü yukarı kaldır ve seksi bir göbek dansı yap.",
            "Partnerinin karnını baştan aşağı yala.",
            "Ağzına biraz ılık su al ve daha sonra boynumun her yerine ılık öpücükler kondur.",
            "2 tur boyunca partnerine itaatkar ol.",
            "Mutfağa gidelim ve yemek yapıyormuş gibi yapalım. Sonra beni yavaşça baştan çıkarmanın bir yolunu bul.",
            "Bir buz al ve boynumdan başlayıp ayak parmaklarıma kadar seksi bir iz bırak.",
            "Önümüzdeki beş dakika boyunca patron benim ve benim seksi emirlerimi yerine getirmek zorundasın.",
            "Yanıma uzan. Bakmadan vücudumun en özel bölgelerinde elini gezdir.",
            "Partnerinin poposunu öp.",
            "Ağzınla Üstümden bir şeyi çıkart.",
            "Partnerinin poposunu yala.",
            "Partnerinin ayağını yala.",
            "Birkaç saniye boyunca parmaklarımı em. Şimdi meme uçlarımın etrafında ve daha sonra da göbek deliğimde gezdir.",
            "Partnerin karnından aşağıya biz buz küpü kaydırsın.",
            "Bana bir seks oyuncağı satmaya Çalışıyormuş gibi yap. En iyi satış konuşmanı yap.",
            "Partnerinin iç çamaşırlarından birini giy.",
            "İlkel bir şekilde partnerinin saçını kibarca çek.",
            "Meme uçlarımın etrafına dudak balmı yada ruj sür, daha sonra direkt vücudumdan dudaklarına sür.",
            "Partnerine/aşık olduğun insana aşkını ilan etmek için 4 satırlık kısa bir şiir uydur.",
            "Aynı anda iki bölgemi uyar. Bir bölgede ellerini kullan, diğerinde de dudaklarını.",
            "Hiç sözcük kullanmadan gözlerini kullanarak bana şehvetli bir mesaj göndermeye çalış.",
            "Üstümü parçalayarak çıkart ve seksi bir öpücük ver.",
            "Barda bir yabancıymışım gibi davran. Eve seninle gelmem için beni ikna etmeye çalış.",
            "Önünde duracağım. Mümkün olan en yavaş şekilde beni soy.",
            "Partnerinin taklidini yap.",
            "Partnerin yerde yatarken üstünde 3 şınav çek ve onu öp.",
            "Etrafına bak ve seks oyunumuza ekleyebileceğin bir şey bul.",
            "Kıyafetlerin üstünde kalarak iç çamaşırlarını çıkart.",
            "Grubundan birini tahrik et.",
            "Grubundan birinin en hoşlandığı seksi kelimeyi söyle.",
            "Seksi bir dans yapın.",
            "Birine nazik bir masaj yapın.",
            "Twitter'a uygunsuz bir şeyler yazın.",
            "Dudaklarım hariç yüzümün her yerine şehvetli öpücükler kondur.",
            "Partnerinin adını kulağına seksi bir şekilde fısılda.",
            "Karşı cinsten birinin kasıklarına dokun.",
            "Karşı cinsten birinin belinden sar.",
            "Karşı cinsin sırtında tırnaklarını gezdir.",
            "Partnerine Nude at.",
            "Sadece öperek partnerini heyecanlandırmak için on saniyen var. Dudaklarla sınırlı değilsin.",
            "Alt dudağımı 30 saniye boyunca em.",
            "Partnerinin elini tut ve cinsel organına götür.",
            "Dişlerinin arasına karşı cinsin meme ucunu al.",
            "Karşı cinsin boynunu morart.",
            "Partnerini tutkuyla öp.",
            "Dövmenin bende seksi olacağını düşündüğün yeri ağzınla göster. Dilinle çiz.",
            "Partnerinin kasığından öp.",
            "Popoma masaj yap.",
            "Partnerinin ayağına masaj yap.",
            "Üstümdeki her 1.000$ için karşı cinsten birinin üstünü çıkarttır.",
            "Beni domalt ve götüme şaplak at.",
            "Partnerinin burnunu yala.",
            "Partnerinin yalağını yala.",
            "Sen doktorsun, ben de senin hastan. Beni seksi seksi muayene et.",
            "Cinsel organıma değecek şekilde twerk yap.",
            "Karşındakinin Cinsel bölgesini yala",       
        }
    },
    ["parti"] = {
        ["dogruluk"] = {
            "Hiçbir zaman bir şeyi çalmadın mı?",
            "Hiç kimseyi gizlice izlemedin mi?",
            "Hiçbir zaman birini kıskandın mı?",
            "Hiçbir zaman birinin sınav kağıdına bakmadın mı?",
            "En utanç verici anın nedir?",
            "En sevmediğin yemek nedir ve neden?",
            "Hiçbir zaman bir şeyi yanlışlıkla kırmadın mı?",
            "Hiç kimseyi arkasından konuştun mu?",
            "En sevdiğin film nedir ve neden?",
            "Hiçbir zaman birisine aşık oldun mu?",
            "Hiçbir zaman başka birine sahte bir isim vermedin mi?",
            "En utanç verici moda seçimin nedir?",
            "En sevdiğin şarkı nedir ve neden?",
            "Hiç kimseyi gerçekten kızdırdın mı?",
            "Hiçbir zaman biriyle sırlarını paylaşmadın mı?",
            "En sevdiğin tatil hangisi ve neden?",
            "Hiçbir zaman birisine sahte bir hikaye anlatmadın mı?",
            "Hiçbir zaman birine yalan söylemedin mi?",
            "En utanç verici dans hareketin nedir?",
            "Hiç kimseyi kıskanmadın mı?",
            "Hiç bir zaman birinin arkasından konuştun mu?",
            "Hangi yemeklerden hoşlanmıyorsun ve neden?",
            "Hiç sınavda kopya çektin mi?",
            "En sevmediğin öğretmen kim ve neden?",
            "Hiçbir zaman birine aşık oldun mu?",
            "En utanç verici anın neydi?",
            "En sevmediğin şarkı nedir?",
            "Hiçbir zaman yalan söyledin mi?",
            "Hiç suçsuz olduğun bir şeyden ceza aldın mı?",
            "Hangi film seni en çok etkiledi ve neden?",
            "Hiç biri seni ağlattı mı?",
            "En utanç verici anın neydi?",
            "En utanç verici moda seçimin neydi?",
            "Hiçbir zaman bir partide çok içtin mi?",
            "En utanç verici dans hareketin nedir?",
            "En kötü alışkanlığın nedir?",
            "En sevdiğin yemek nedir ve neden?",
            "En utanç verici cep telefonu arka planın neydi?",
            "Hiçbir zaman bir kıza/erkeğe açılmaya cesaret edemedin mi?",
            "En çok utanç veren yemeğin nedir?",
            "Hiçbir zaman birinin arkasından konuştun mu?",
            "Hangi yemeği en son mide bulantısıyla yedin?",
            "En sevmediğin öğretmen kimdi ve neden?",
            "Hiçbir zaman birine aşık oldun mu?",
            "Hangi yemekleri sevmediğini söyleyip aslında sevdiğin oldu mu?",
            "En utanç verici anın neydi?",
            "En sevmediğin şarkı nedir?",
            "Hiçbir zaman yalan söyledin mi?",
            "Hiçbir zaman bir sınavda kopya çektin mi?",
            "En kötü alışkanlığın nedir?",
            "Hangi filmler seni en çok etkiledi ve neden?",
            "En utanç verici moda seçimin neydi?",
            "Hiçbir zaman bir partide çok içtin mi?",
            "En utanç verici dans hareketin nedir?",
            "En sevdiğin yemek nedir ve neden?",
            "Hiçbir zaman biriyle kavga ettin mi?",
            "En utanç verici cep telefonu arka planın neydi?",
            "Hiçbir zaman bir kıza/erkeğe açılmaya cesaret edemedin mi?",
            "Hangi şarkıyı defalarca dinledin ama hala nasıl söylendiğini bilmiyorsun?",
            "En kötü saç kesimini kim yaptı ve neden bu kadar kötü olduğunu düşünüyorsun?", 
        },
        ["cesaret"] = {
            "Birbirimizi aynı anda arayalım ve telefonu açana 'Seni seviyorum' deyin.",
            "Yerden bir şey almadan 10 dakika kadar tavanda durun.",
            "Bir bardak suyu üstünüze dökün.",
            "En sevdiğin şarkıyı söyleyin, ancak başınızı bir kova suya sokun.",
            "En sevmediğin yemeği yiyin.",
            "Kollarınızı ve bacaklarınızı havada sallayın ve öylece 30 saniye kalın.",
            "Bir buz küpü alın ve onu bir dakika boyunca ağzınızda tutun.",
            "Diş macunu ile tuz karışımını tadın.",
            "En sevdiğiniz film repliğini bir şarkı söylermiş gibi söyleyin.",
            "Arkadaşlarınıza bir komik dans gösterisi yapın.",
            "Dudaklarınızı bir dakika boyunca kapatın ve şarkı söyleyin.",
            "Giyim tarzınıza tamamen zıt bir şey giyin ve öyle kalın.",
            "Başınızı bir kovaya su doldurun ve öylece 30 saniye kalın.",
            "En utanç verici anınızı anlatın.",
            "Herkesin önünde biraz ayakta dans edin.",
            "Bir dilim limon yiyin.",
            "En sevdiğiniz şarkıyı söyleyin, ancak ağzınızda su tutun.",
            "Biraz çim yiyin.",
            "Yanınızdaki kişiyi kollarınızdan asın ve öylece bir dakika kalın.",
            "En utanç verici fotoğrafınızı gösterin.",
            "Bir kova suyu başınıza dökün.",
            "Önünüzdeki kişiye körü körüne güvenin ve onun sizi yönlendirmesine izin verin.",
            "Yüzünüze bir topu atın ve yakalamaya çalışın.",
            "Bir şarkı söyleyin, ancak sözleri değiştirin ve o anki duruma uygun hale getirin.",
            "Arkadaşlarınızın istediği bir şarkıyı söyleyin.",
            "Bir dilim soğan yiyin.",
            "Bir kova su ile kafanızı yıkayın.",
            "Önünüzdeki kişinin saçlarını tarayın.",
            "En utanç verici anınızı canlandırın.",
            "Başınıza bir buz koyun ve öylece 30 saniye kalın.",
            "En sevmediğiniz hayvanı taklit edin.",
            "Kafanıza bir nesne koyun ve öylece bir dakika kalın.",
            "En sevdiğiniz yemeği yapın ve herkesin tadına sunun.",
        }
    },
    ["cilgin"] = {
        ["dogruluk"] = {
            "Buradaki insanlar arasından kiminle çıkmak isterdin?",
            "Hayatında yaptığın en utanç verici şey ne?",
            "İlk görüşte aşka inanır mısın?",
            "Biriyle sonsuza kadar yaşamak istesen bu kim olurdu?",
            "Son erkek veya kız arkadaşınla nasıl ayrıldınız?",
            "Burada sana göre en kötü ilişkiyi hangi çift geçirir?",
            "Kişisel kahramanın kim?",
            "Burada en sevmediğin veya en az sevdiğin kişi kim?",
            "En büyük korkun ne?",
            "Birinin sana söylediği en son sırrı dökül.",
            "Hoşlandığın kişi kim?",
            "Buradan birisini köle almak istesen bu kim olurdu? ne yaptırmak isterdin?",
            "Beş kelimeyle kendini tanımla!",
            "En son kiminle ne kavgası ettin?",
            "Bu odada herkes hakkında fikrini açıkla.",
            "Birine aşık mısın? aşıksan onu biraz tanımla.",
            "1 yıl boyunca bir adada mahsur kalsan yanına ne alırdın?",
            "Tekrar doğma şansın olsaydı ne olmak isterdin?",
            "Burada en çekici bulduğun erkek/kız kim?",
            "Kim kötü bir ebeveyn olur?",
        },
        ["cesaret"] = {
            "Daha önce hiç yakın arkadaşlarından birine aşık oldun mu?",
            "Bir arkadaşınla sanki yabancıymışsın gibi flört et.",
            "Bize bir çocuk şarkısı söyle.",
            "Herkes yer değiştirsin!",
            "Günün geri kalanı boyunca arkadaşların tarafından seçilen bir kıyafeti giy",
            "Mümkün olduğu kadar fazla insan içermek üzere grupça kucaklaşın.",
            "Gece boyunca her tuvalete çıkman gerektiğinde karşı cinsten biriyle beraber gitmek zorundasın.",
            "5 tur boyunca bir kişiye Daddy/Mommy diye seslen.",
            "1 tur boyunca sağındaki insanın kucağında otur.",
            "2 tur boyunca oyundan atıldın!",
            "Diğerleri tarafından seçilen birisi ile dans et.",
            "Televizyondan ünlü bir kişinin taklidini yap.",
            "Sağındaki insanın taklidin yaparak onunla dalga geç.",
            "Bu odadaki birini taklit et ve diğerlerinin tahmin etmesine izin ver!",
            "Herkes hep beraber bir şarkı söylemeli. Hangi şarkı olacağına sen karar ver!",
            "Karşı cinsten biriyle eşleş, ikiniz ilk bebeklerine sahip olmak üzere olan mutlu bir çiftsiniz. 5 dakika boyunca bir doğum sahnesi canlandırın!",
            "Oynayan herkesi 5 saniyeliğine öp.",
            "Sol tarafındaki kişi birini seçsin ve o kişiye çıkma teklifi et!",
            "Komik bir grup fotoğrafı çekilip sosyal medyada paylaşın!",
            "Hiç durmadan 3 dakika boyunca kendini anlat!",
        }
    },
    ["karisik"] = {
        ["dogruluk"] = {
            "Eğer biri senin hayatın hakkında bir film yapsaydı ismi ne olurdu? Rolünü kim oynardı?",
            "En kötü öpüşmen hangisiydi?",
            "Hiç hesabı ödemeden bir restorandan ayrıldın mı?",
            "Hiç sevgilini aldattın mı?",
            "Odadaki oyuncular hakkında ne düşünüyorsun?",
            "Masturbasyon yaptığın en uygunsuz yer neresi?",
            "En sevdiğin porno sitesi?",
            "Bu odadaki en güzel kişi kim?",
            "Şehirdeki en kıskandığın kişi kim?",
            "Seni eski sevgilinle tekrar bir araya getirebilecek şey nedir?",
            "Tanıdığın en sinir bozucu kişi kim",
            "Yediğin en garip şey ne?",
            "Bir ünlü olsan hangisi olurdun?",
            "Daha önce hiç çıplak yüzdün mü?",
            "Sence en çekici pornocu kim?",
            "Bir insanda en nefret ettiğin şey ne?",
            "Eğer fiziksel görünüşünle ilgili bir şeyi değiştirme şansın olsa ne olur?",
            "Sağ tarafındaki kişiye tanıdığın biriyle seks yapıp yapmadığını sor.",
            "Daha önce hiç karşı cinse ait bir iç  çamaşırı giydiniz mi?",
            "Hiç aynı cinsten birine abayı yaktın mı?",
            "Cep telefonun olmadan dayanabileceğin en uzun süre sence ne kadar?",
            "İlk nerede seviştin?",
            "Aşık olduğun biri varmı ?",
            "Bu odadaki tüm insanlar arasında kiminle çıkmak isterdin?",
            "Arkadaşının sevgilisi olsa dahi o karşı cinse bir şeyler hissettin mi?",
            "Buradaki kişiler arasında en kötü giyinen kim?",
            "Buradaki kişiler arasında en seksi giyinen kim?",
            "Buradaki kişiler arasında en güzel giyinen kim?",
            "Sence zeka mı güzellik mi?",
            "Daha önce hiç bir erkek arkadaşının kardeşini yada arkadaşını öptün mü?",
            "En kötü alışkanlığın ne?",
            "Sinirini bozan şey ne?",
            "Hak etmeyen birine yaptığın en kötü şey neydi?",
            "Ağzına aldığın en iğrenç şey ne?",
            "Ağladığın en salak sebep neydi?",
            "Hiç çok sarhoşluktan yatağını ıslattın mı?",
            "Seks esnasında çok ses çıkarır mısın?",
            "En sevdiğin oyuncak hayvanının ismi neydi?",
            "Bu odada kiminle takılmak en kolay",
            "Yapıp da tamamen utanç duyduğun bir şeyden bahset.",
            "Fetiş Sahibi misin?",
            "Yapabileceğin en kötü iş nedir?",
            "Annenin yaptığı en sevdiğin yemek ne?",
            "Favori Disney karakterin kim?",
            "Hayatındaki ilk hatırladığın anın ne?",
            "Hangi ünlüye aşıksın?",
            "Nelerden korkarsın?",
            "Favori filmin hangisi?",
            "Şimdiye kadar çıktığınız birine yaptığınız en tatlı şey nedir?",
            "Böceklerden korkar mısın?",
            "Annen mi Baban mı?",
            "Her gün 5 saat ekstra zamanın olsa neye harcardın?",
            "Herhangi bir spor dalında bir sporcu olsan bu hangi spor olurdu?",
            "Bir gün nasıl bir insanla evlenmek istiyorsun?",
            "Babanın yaptığı en sinir bozucu şey ne?",
            "Birine aşık mısın?",
            "Bu ortamda en çok ilgini çeken kim? (Karşı cins için)",
            "Bu ortamdan biriyle bir tatile gideceksin bu kim olurdu? (karşı cins ile)",
            "En son ne zaman banyo yaptın?",
            "Hayalindeki Meslek?",
            "Issız bir adaya düştün ve iki şey alacaksın bunlar ne olurdu?",
            "Boğularak ölmek mi? Yanarak ölmek mi?",
            "Ölmemek için dostunu satar mısın?",
            "Aşk mı Para mı?",
            "Sevdiğin kişi ile famfakir açlıktan ölecek şekilde yaşamak mı? yoksa hiç sevmediğin 80 yaşındaki ama ultimilyoner kişi ile yaşamak mı ?",
            "Kimsenin bilmediği bir şey söyle.",
            "Bir şey icat edebilseydin bu ne olurdu?",
            "Eğer gelecekten bir şey bilebilecek olsan bu ne olmasını isterdin?",
            "Sence nasıl bir hata bir ilişkiyi bitirmek için yeterlidir?",
            "İlk ne zaman öpüştün? Anlat.",
            "Daha önce karşı cinsten birini (Ailen haricinde) ilk defa çıplak gördüğün anı hatırlıyor musun? Ne düşündün?",
            "Son erkek arkadaşınla nasıl ayrıldın?",
            "Hem cinsine ilgi duyuyor musun?",
            "En romantik hatıranız neydi?",
            "Libidon yüksek midir?",
            "Seks'e açık birisimisin?",
            "Okula gitmemek için hiç hasta numarası yaptın mı?",
            "Birinin senden öpücük alması için o kişinin ne yapması gerekir?",
            "Yeni tanıştığın biri bir anda seni dudağından öpse ne yaparsın?",
            "Flört'ün seni bir anda dudağından öpse ne yaparsın? (Daha önce hiç öpüşmemişsiniz)",
            "En büyük yalanın nedir?",
            "En sevdiğin renk nedir?",
            "Hiç yara izin var mı? varsa nasıl oldu?",
            "Hiç dövmen var mı? Varsa anlamı ne?",
            "Ailen eve karşı cins getirdiğini görürse tepkisi nasıl olur?",
            "Kitap yazsan konusu ne olurdu?",
            "Daha önce hiç birine zorbalık yaptın mı?",
            "Gözünün önünde karşı cinsin taciz edilse ne yaparsın?",
            "Hiç ev boşken çıplak evde dolaştın mı?",
            "Daha önce hiç erotik rüya gördün mü?",
            "Hiç rüyanda hallendin (Boşaldın mı) mi?",
            "Adını değiştirmeyi hiç düşündün mü? düşündüysen ne?",
            "Sosyal medyaya koyduğun en utanç verici şey ne?",
            "Rüyanda en son ne gördün?",
            "Gittiğin en iyi parti?",
            "Soruyu sen seç istediğin soruyu karşındakine sor.",
            "Aynanın önünde yaptığın en tuhaf şey ne?",
            "Daha önce başka biriyle duş aldın mı?",
            "Siz kızlar/erkekler hiç birbirinize ne kadar büyük dediğiniz oldu mu?",
            "Geçmişindeki pişmanlığın nedir?",
            "Geçmişinden neyi değiştirmek isterdin?",
        },
        ["cesaret"] = {
            "20 Şınav çek",
            "T-Shirt'ini çıkart.",
            "2 Tur boyunca yanındakinin kucağında otur.",
            "Erkek için: Makyaj yap. Kız için: Makyajını sil.",
            "1 Tur boyunca herkesin konuşmasını tekrarla.",
            "Tekrar Soru seç.",
            "Şarkı söyle.",
            "Denize üstün ile atla.",
            "Böcek ye.",
            "Denize üstünü çıkartıp atla.",
            "Soğuk bir espri yap.",
            "Sağ yanındakini yanağından öp.",
            "Telefonunda en son kiminle mesajlaştın? Oku.",
            "Havla.",
            "Miyavla.",
            "Etrafındaki en zayıfı havaya kaldır.",
            "Sağ tarafındakini kucağına al.",
            "1 tur boyunca fısılda.",
            "Herkes Yer değiştirsin.",
            "Tişörtünü veya bikini üstünü 5 saniyeliğine çıkart.",
            "Seksi bir dans yap.",
            "Dudaklarını hareket ettirmeden konuş",
            "Yanında insanın telefonundaki bir kişiye müstehcen şeyler yazmasına izin ver.",
            "Sağındaki insanla tişörtünü çıkart.",
            "Bir kişinin göbek deliğine dil at.",
            "Odadaki en güzel kızla oynaş",
            "İstediğin 2 oyuncuyu (Karşı cins) birbirleriyle öpüştür.",
            "Sağ tarafındaki kişinin ayağının altını yala.",
            "Bir kızın göğüslerinin arasından bir shot iç",
            "Oyunculardan birinin (sen seç) ayak parmağını, bir kulak memesini ve dirseğini yala.",
            "Herkesi dudağından öp",
            "Sol tarafındaki kişiye sadece dudaklarını kullanarak bir şeker ver.",
            "Birisi seni tokatlasın.",
            "Sağ tarafdaki bir oyuncuyla oynaş.",
            "2 dakika boyunca karşı cinsten biriyle seviş.",
            "Herkesi etrafında topla 10 saniye boyunca dön ve karşına çıkanı öp.",
            "Sağındaki kişi sana bir şey söylesin ve twitter'da bunu paylaş.",
            "Birinin göbek deliğinden alkol iç.",
            "Kendi ayak parmağını öp.",
            "Herkese kendinle ilgili utanç verici bir olay anlat.",
            "Striptiz yap.",
            "Birini seç ve götüne şaplak atmasına izin ver.",
            "15 saniye duvarla seviş.",
            "Seninle fransız öpücüğü yapacak birini seç",
            "Alkolü kafana dik.",
            "Herkesin ayağını kokla ve kokularını oyla.",
        }
    }
}

RegisterNUICallback('close', function()
    SetNuiFocus(false, false)
end)

RegisterNUICallback('select', function(data)
    secilen = oyunayarlari[data.label][data.select]
    local playerPed = PlayerPedId()
    local players, nearbyPlayer = QBCore.Functions.GetPlayersFromCoords(GetEntityCoords(playerPed), 20.0)

    SetNuiFocus(false, false)

    if data.label == "klasik" then
        bolum = "Klasik"
    elseif data.label == "cilginparti" then
        bolum = "Çılgın"
    elseif data.label == "ekstrem" then
        bolum = "Ekstrem"
    elseif data.label == "cift" then
        bolum = "Yaramaz"
    elseif data.label == "parti" then
        bolum = "Parti"
    elseif data.label == "cilgin" then
        bolum = "Çılgın"
    elseif data.label == "karisik" then
        bolum = "Karisik"
    end

    if data.select == "dogruluk" then
        ne = "D"
    else
        ne = "C"
    end

    secilen = secilen[math.random(1, #secilen)]

    SendNUIMessage({
        type = "txt", 
        html = secilen
    })
    
    for i = 1, #players, 1 do
        TriggerServerEvent("ed-truthordare:server:send", secilen, bolum, ne, GetPlayerServerId(players[i]))
    end
end)

RegisterNetEvent("ed-truthordare:openNUI", function()
    SetNuiFocus(true, true)
    SendNUIMessage({
        type = "open", 
    })
end)